// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyrQ_jV3eHUEsY9NFbq6EA5SuJ5pJGULE',
    appId: '1:737115000801:web:ffde6cf4cd62396b818ca0',
    messagingSenderId: '737115000801',
    projectId: 'xni75w9l4qcdp0p0xnbergczhoxgud',
    authDomain: 'xni75w9l4qcdp0p0xnbergczhoxgud.firebaseapp.com',
    storageBucket: 'xni75w9l4qcdp0p0xnbergczhoxgud.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABkVVCgPq1cb2PpZWubKufM7zTpVLCVMI',
    appId: '1:737115000801:android:3719715b6dacf71d818ca0',
    messagingSenderId: '737115000801',
    projectId: 'xni75w9l4qcdp0p0xnbergczhoxgud',
    storageBucket: 'xni75w9l4qcdp0p0xnbergczhoxgud.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw-BA9zHW4Yh58ev3W2RuxgOSgFnORe7I',
    appId: '1:737115000801:ios:4389a4affe98a5ca818ca0',
    messagingSenderId: '737115000801',
    projectId: 'xni75w9l4qcdp0p0xnbergczhoxgud',
    storageBucket: 'xni75w9l4qcdp0p0xnbergczhoxgud.firebasestorage.app',
    iosBundleId: 'com.mycompany.CounterApp',
  );
}
